// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs_sKoy4zaeuCsFgWmLSZscoUCdrLwR-8',
    appId: '1:311106769503:web:08dc4c7919221fc04ac1ea',
    messagingSenderId: '311106769503',
    projectId: 'trackmyclass-7048f',
    authDomain: 'trackmyclass-7048f.firebaseapp.com',
    storageBucket: 'trackmyclass-7048f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4_EcBSdS7SCYd1t4wrIVRXlDzCdutyX0',
    appId: '1:311106769503:android:c713034b6ef03fb94ac1ea',
    messagingSenderId: '311106769503',
    projectId: 'trackmyclass-7048f',
    storageBucket: 'trackmyclass-7048f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP0Ev8tHhzm6w_EmZnu-WqqIDwHTbsOgg',
    appId: '1:311106769503:ios:72e1940984d5929a4ac1ea',
    messagingSenderId: '311106769503',
    projectId: 'trackmyclass-7048f',
    storageBucket: 'trackmyclass-7048f.firebasestorage.app',
    iosBundleId: 'com.example.trackmyclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP0Ev8tHhzm6w_EmZnu-WqqIDwHTbsOgg',
    appId: '1:311106769503:ios:72e1940984d5929a4ac1ea',
    messagingSenderId: '311106769503',
    projectId: 'trackmyclass-7048f',
    storageBucket: 'trackmyclass-7048f.firebasestorage.app',
    iosBundleId: 'com.example.trackmyclass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs_sKoy4zaeuCsFgWmLSZscoUCdrLwR-8',
    appId: '1:311106769503:web:bf3defc469f841224ac1ea',
    messagingSenderId: '311106769503',
    projectId: 'trackmyclass-7048f',
    authDomain: 'trackmyclass-7048f.firebaseapp.com',
    storageBucket: 'trackmyclass-7048f.firebasestorage.app',
  );
}
